//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.03 at 05:10:40 PM IST 
//


package org.example.eligibleproductinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EligibleProductType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EligibleProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.example.org/EligibleProductInfo}ProductId"/>
 *         &lt;element ref="{http://www.example.org/EligibleProductInfo}ProductDescription"/>
 *         &lt;element ref="{http://www.example.org/EligibleProductInfo}IsActive"/>
 *         &lt;element ref="{http://www.example.org/EligibleProductInfo}IsMutuallyExclusive"/>
 *         &lt;element ref="{http://www.example.org/EligibleProductInfo}MutuallyExclusiveProduct" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EligibleProductType", propOrder = {
    "productId",
    "productDescription",
    "isActive",
    "isMutuallyExclusive",
    "mutuallyExclusiveProduct"
})
public class EligibleProductType {

    @XmlElement(name = "ProductId")
    protected int productId;
    @XmlElement(name = "ProductDescription", required = true)
    protected String productDescription;
    @XmlElement(name = "IsActive")
    protected boolean isActive;
    @XmlElement(name = "IsMutuallyExclusive")
    protected boolean isMutuallyExclusive;
    @XmlElement(name = "MutuallyExclusiveProduct")
    protected MutuallyExclusiveProductType mutuallyExclusiveProduct;

    /**
     * Gets the value of the productId property.
     * 
     */
    public int getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     */
    public void setProductId(int value) {
        this.productId = value;
    }

    /**
     * Gets the value of the productDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * Sets the value of the productDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductDescription(String value) {
        this.productDescription = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     */
    public boolean isIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     */
    public void setIsActive(boolean value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the isMutuallyExclusive property.
     * 
     */
    public boolean isIsMutuallyExclusive() {
        return isMutuallyExclusive;
    }

    /**
     * Sets the value of the isMutuallyExclusive property.
     * 
     */
    public void setIsMutuallyExclusive(boolean value) {
        this.isMutuallyExclusive = value;
    }

    /**
     * Gets the value of the mutuallyExclusiveProduct property.
     * 
     * @return
     *     possible object is
     *     {@link MutuallyExclusiveProductType }
     *     
     */
    public MutuallyExclusiveProductType getMutuallyExclusiveProduct() {
        return mutuallyExclusiveProduct;
    }

    /**
     * Sets the value of the mutuallyExclusiveProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link MutuallyExclusiveProductType }
     *     
     */
    public void setMutuallyExclusiveProduct(MutuallyExclusiveProductType value) {
        this.mutuallyExclusiveProduct = value;
    }

}
